kind: pipeline
type: docker
name: Deployment

trigger:
  event:
    - push

steps:
  - name : pullsubmodule
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: docker-build-and-push
    image: plugins/docker
    settings:
       dockerfile: Dockerfile
       context: .
       registry: hub.codefirst.iut.uca.fr
       repo: hub.codefirst.iut.uca.fr/mateo.centeno/portfolio
       username:
         from_secret: SECRET_REGISTRY_USERNAME
       password:
         from_secret: SECRET_REGISTRY_PASSWORD